### ISSUE TITLE
Colcon metas regex support.

### ISSUE THREAD

**Issue by BorjaOuterelo** [colcon/colcon-metadata#19]
I am trying to use a `colcon.meta` file and I require to pass a flag to several of my packages. It is the same flag for a subset of my packages.
Is there any chance to have the ability to use a regular expression pattern either in the place of a name or a different mode: "pattern"?

```
{
    "names":{
        ".*_no_shared":{
            "cmake-args":[
                "-DBUILD_SHARED_LIBS=OFF",
            ]
        }
}
```

```
{
    "pattern":{
        ".*_no_shared":{
            "cmake-args":[
                "-DBUILD_SHARED_LIBS=OFF",
            ]
        }
}
```

Is there anything in colcon that covers my requirement?
I would be happy to help with this with a PR.

**Comment by dirk-thomas** [comment]
At the moment this is not possible. Adding support for this use case sounds good to me. I think a separate category makes most sense to ensure to avoid complicating the processing of the simple `names` category. Since there is also a `paths` category I think the new category name needs to be a bit more specific, e.g. `names-regex`. Any contribution for this would be welcome.

**Comment by dirk-thomas** [comment]
@BorjaOuterelo Are you still interested to contribute a pull request for this feature idea?

**Comment by dirk-thomas** [comment]
@BorjaOuterelo Friendly ping.

**Comment by BorjaOuterelo** [comment]
Hi, @dirk-thomas. Sorry for the late response. I had not done any further development regarding this feature. At the moment I don't envision doing this in the mid-long term.

**Comment by dirk-thomas** [comment]
Thanks for the feedback. I will go ahead and close the ticket for now. Any pull request towards this is of course appreciated.
